script: 
  - docker run --rm --volume "$(pwd):/data" --user $(id -u):$(id -g) pandoc/latex README.md -o README.docx

deploy:
  - provider: script
    script: bash .travis/add_to_git.sh
    skip_cleanup: true
    on:
      branch: main